version: '3.8'

services:
  server:
    build: ./server
    command: uvicorn playola.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8004:8000
    env_file:
    - path: ./.env
      required: false
    depends_on:
        - server-db

  server-db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db-initializer:
    build: ./server
    command: sh ./db/reset_db.sh
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - server-db
      - server

  admin-react:
    build: 
      context: ./admin-react-app
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./admin-react-app:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
    - path: ./.env
      required: false
    ports:
      - 3000:3000
      - 3010:3010
