version: '3.8'

services:
  server:
    build: ./server
    command: uvicorn playola.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8004:8000
    env_file:
    - path: ./.env
      required: false
    depends_on:
        - server-db

  server-db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

 
